guidance: "prop_nav"
mission: "BallisticAttackFromRight"
simulation:
  target_fps: 10
  sim_n_steps: 120
  blast_radius: 4
target:
  start_x: 301
  start_y: 100
  speed: 4
interceptor:
  start_x: 0
  start_y: 0
  speed: 3

